### ISSUE TITLE
Tutorial/Quickstart is Outdated

### ISSUE THREAD

**Issue by Denis-Step** [googleapis/python-translate#157]
OS: Mac Big Sur
Python 3.9
```

Internal Server Error: /api/translate
Traceback (most recent call last):
  File "/Users/denisstepanenko/Projects/tkdeux/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/denisstepanenko/Projects/tkdeux/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisstepanenko/Projects/tkdeux/tkdeux/studies/views.py", line 64, in translate_document
    return HttpResponse(translate_text(request.GET.get('text', "Hello")))
  File "/Users/denisstepanenko/Projects/tkdeux/tkdeux/studies/views.py", line 50, in translate_text
    response = client.translate_text(
TypeError: translate_text() got an unexpected keyword argument 'request'
```

I didn't bother to provide more information because the Python client library install didn't even work and I had to StackOverflow the answer. Is this all outdated?

Thanks!

**Comment by munkhuushmgl** [comment]
@Denis-Step 
Can u share your package version of google-cloud-translate?

**Comment by Denis-Step** [comment]
I made a mistake. I was indeed using v2. I don't know why it installed version 2, maybe I used `pip install ` by accident instead of `pip3`? Anyway, thanks for responding and sorry for the false alarm. The docs are kind of hard to read though and 404 on some pages but this was my fault.
