### ISSUE TITLE
unexpected keyword argument 'glossary_config'

### ISSUE THREAD

**Issue by zphj1987** [googleapis/python-translate#53]
#### Code 
```python
def translate_text_with_glossary(
    text="YOUR_TEXT_TO_TRANSLATE",
    project_id="YOUR_PROJECT_ID",
    glossary_id="YOUR_GLOSSARY_ID",
):
    """Translates a given text using a glossary."""

    client = translate_v3.TranslationServiceClient()

    glossary = client.glossary_path(
        project_id, "us-central1", glossary_id  # The location of the glossary
    )

    glossary_config = translate_v3.types.TranslateTextGlossaryConfig(
        glossary=glossary)

    # Supported language codes: https://cloud.google.com/translate/docs/languages
    response = client.translate_text(
        contents=["mozha Hello world"],
        target_language_code="en-US",
        source_language_code="zh-CN",
        parent="xxxxxxxx",
        glossary_config=glossary_config,
    )
    print(response)
    print("Translated text: \n")
    for translation in response.glossary_translations:
        print(u"\t {}".format(translation.translated_text))

```

```bash
[root@lab101 3-google-translate]# pip-3 list|grep google-cloud-translate
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
google-cloud-translate (3.0.1)
```
```bash
[root@lab101 3-google-translate]# python3 translate_google.py 
Traceback (most recent call last):
  File "translate_google.py", line 37, in <module>
    translate_text_with_glossary("xxxxxxx","xxxxxxxxxx","xxxxxxxxx")
  File "translate_google.py", line 30, in translate_text_with_glossary
    glossary_config=glossary_config,
TypeError: translate_text() got an unexpected keyword argument 'glossary_config'
```

**Comment by munkhuushmgl** [comment]
I will look into it.

**Comment by munkhuushmgl** [comment]
@zphj1987 there was breaking change related to `types`, so there is no types.
You probably need to use the following code: (note that types.TranslateTextGlossaryConfig is gone.)
```
def translate_text_with_glossary(
    text="YOUR_TEXT_TO_TRANSLATE",
    project_id="YOUR_PROJECT_ID",
    glossary_id="YOUR_GLOSSARY_ID",
):
    """Translates a given text using a glossary."""

    client = translate.TranslationServiceClient()
    location = "us-central1"
    parent = f"projects/{project_id}/locations/{location}"

    glossary = client.glossary_path(
        project_id, "us-central1", glossary_id  # The location of the glossary
    )

    glossary_config = translate.TranslateTextGlossaryConfig(
        glossary=glossary)

    # Supported language codes: https://cloud.google.com/translate/docs/languages
    response = client.translate_text(
        request={
            "contents": [text],
            "target_language_code": "ja",
            "source_language_code": "en",
            "parent": parent,
            "glossary_config": glossary_config
        }
    )

    print("Translated text: \n")
    for translation in response.glossary_translations:
        print(u"\t {}".format(translation.translated_text))
```\
